#!/usr/bin/env python
# geneaTD - A multi-touch tower defense game.
# Copyright (C) 2010-2011 Frederic Kerber, Pascal Lessel, Michael Mauderer 
#
# geneatd is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# geneatd is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#For more information contact the geneaTD team: info@geneatd.de
#

import sys

try:
    import geneatd
except ImportError:
    sys.path = ['..', '/usr/share/games'] + sys.path

    try:
        import geneatd
    except ImportError:
        sys.stderr.write('ERROR: Cannot find geneatd package: reinstall the game.\n')
        sys.exit(1)

if __name__ == '__main__':
    geneatd.GeneaTD.start()
